### ISSUE TITLE
Create a service instead of using rc.local

### ISSUE THREAD

**Issue by StevenCregan** [OutsourcedGuru/pizero-webcam-tutorial#2]
I prefer making an easily restartable service to help with tuning resolution/framerate options
My config is similar to this:

Filename: `mjpg_streamer.service`
Location: `/lib/systemd/system/`

Contents:
```
[Unit]
Description=MJPG Streaming Service
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/pi
ExecStart=/home/pi/mjpg-streamer/mjpg-streamer-experimental/mjpg_streamer -o "/usr/local/lib/mjpg-streamer/output_http.so -w /home/pi/mjpg-streamer/mjpg-streamer-experimental/www" -i "/usr/local/lib/mjpg-streamer/input_raspicam.so -x 1280 -y 720 -fps 41 -quality 40 -ex sports -ifx none -mm average"
ExecStop=/bin/kill -SIGINT $MAINPID
StandardOutput=journal
StandardError=inherit
SyslogIdentifier="mjpg_streamer"
Restart=always
RestartSec=1
User=root

[Install]
WantedBy=multi-user.target

```

Link by running: `sudo ln -s /lib/systemd/system/mjpg_streamer.service /etc/systemd/system/mjpg_streamer.service`
Refresh systemd: `sudo systemctl daemon-reload`
Enable service: `sudo systemctl enable mjpg_streamer`
Start service for the first time: `sudo systemctl start mjpg_streamer`

**Comment by OutsourcedGuru** [comment]
I think I'm more familiar with `init.d`, to be honest with something like a `sudo service webcamd start` sort of interface. It would likely be more in tune with the original from OctoPi's image [as seen here](https://github.com/guysoft/OctoPi/blob/6d08ff02284040a9136dceccb3fe630923ce2802/src/modules/octopi/filesystem/home/root/bin/webcamd).

**Comment by StevenCregan** [comment]
Yeah, the webcamd service is a lot more robust, and certainly better thought out; This is just a lightweight suggestion I whipped up in the middle of the night 😅
I've just been seeing more and more things on Debian systems moving towards systemd, so that's what I've been trying to familiarize myself with. Figured it'd be worth sharing, even if not necessary 🙂

**Comment by OutsourcedGuru** [comment]
Thanks for the suggestion and it's good to know each one that's available. What I could do is close this issue and create a link to it in the README.

**Comment by StevenCregan** [comment]
Sounds good 👍
